travis:
  secure:
    BINSTAR_TOKEN: KqLtP38efR3H3uI8RMyfrXJ3VHBRRj/Bfxgj9LD1NkFabxcwnUpzncuCJ/QK1Rk7qWrRbP46XsfMF0BwimW/6WgVvq6qjjAH7j5omtC41LbvnXoVt3uLFbUo9OIz19paI9A9/Li3cfSzxbD7AUi2n+7w03FemTCgS0pKFoTolmbCcspPWoCWjFXVxulN+56kXmVNNDN2z1ASY+bcsrs7WHF3BjFY29Klqf9/SMkXnH7VOaLZMPa+5eDaPRDWmmJm2e9Aec3uEqQ9ZV+FLGpQKRA5YhI5Y4uSPH1KoHEcE3xOcqkEQjL7Pw9hpsPQaydY9mRoAHNNWkw6r7GauvOsVUBL6zcndw+sbjoGD5AFsX2g1ROS4cvfO9SXO7lqeiTkwspK2Yr+XysyKzqWQji4GiLrr6F2gdJVmxOnf5DEBPVUld5g2ZGFqDMVSLKNDKTkEeg1l3HlF7paEitJ3/yPzknPy0wJib39dxKfXGrVG85ptDAGLLgGNn6uq1nX3ZRe/gJ3g0f+uqS5f8dpCtrn9Ad3GzNOjlprmfDdwyvMhvbVzv9equO7jyCE2vlOpN1zXbOFCCDHIQhzH0UsRjfsWjEO1TrNbLjr5XwS4y3AxtVFtTnXebRqbzggGUYlMpNRfxnR5i3aaY3M6pYu/qMTINGssieoThqavyW3pAA+vkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
