travis:
  secure:
    BINSTAR_TOKEN: uFSmEKqBFMNsCDnjurIz4mSqV8cD29tUdoYr+LW0Ix9y7oY5U7mRwheGAJ3cetgTVXp0ATsSlQKroNhAyUN+3q9mHkIcB3SW8fS0YwjTRR8GTjZpnx0JdtaFiYRBdaHMABgcPRkjpz/4z/xcyaZqxOX+ilAMDWb+GFd/FiEn1UE6Y9j7jwYEyrIWPK2DF8oRHjIRAK+wY60HMtwK5/HB0KzSeb/Waxn77aash5ErtX8h5woANj3o4aI1BGag0FHm88Calnoe6j+wmtmqtok+AguhXt39PV/s8RDrpaXnuORzlOv4lANbP9X31AATUFCcCqNLnYopLB/E0IqMqPCMmohUjGBkOkg+vW3MIrYPdx4s8uvshG6n8yezE7CAllnLSqEILqHZHtqIfjMYDLbv0t9UW0Wrjw4XykeQ4ZdQefC7lwX0oJRr55q7T7hcldSNSDq+fgUOGqgwOkAa0+nwJycoM5PgYkXxRy9ecf25tZ3wpyvo6rkYp8TraP/VDFB229p3tgHNkxKTPZvfnWcEnCM20VcSvlfsh1ibDGJDxENyS2OsX9AFfBEEWqfb2GegsSLpPH2SFL/lk/fue/QaQgkn2KQGRhSNr4Aoo3KK+BYySlxnVCHmMQ7+7CO5c3hwlKn4MZXBXqP8hnmfoVB8t6PKtKZ4CIHRz6NJiGoBPB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
